export const CLIENT_SERVICES = [
  { code: "IV", name: "Initial Visit" },
  { code: "FV", name: "Follow-up Visit" },
  { code: "DC", name: "Discharge" },
  { code: "SUP", name: "Supervisory Visit" },
  { code: "IDT", name: "IDT Meeting" },
  { code: "OC", name: "On-Call" },
  { code: "RC", name: "Recertification Visit" },
  { code: "SM", name: "Staff Meeting" },
  { code: "IN", name: "In-Service" },
  { code: "EV", name: "Evaluation Visit" },
  { code: "SWV", name: "Social Worker Visit" },
  { code: "INS", name: "Inservice Meeting" },
  { code: "RV", name: "Regular Visit" },
  { code: "BV", name: "Bereavement Visit" },
  { code: "HV", name: "Home Health Aid Visit" },
  { code: "F/UV", name: "Follow Up Visit" },
  { code: "O", name: "Orientation" },
  { code: "VV", name: "Volunteer Visit" },
  { code: "DPV", name: "Death pronouncement" },
  { code: "APV", name: "Admission Visit" },
  { code: "OTH", name: "Other" },
];
export const ACTION_STATUSES = {
  PENDING: "Pending",
  SUCCEED: "Succeed",
  FAILED: "Failed",
  UNDEFINED: undefined,
};
